version: "3.0"

services:
  action_service:
    image: rasa/rasa_core_sdk:latest
    networks: ['rasa-network']
    ports:
      - 5055:5055
    volumes:
      - ./actions:/app/actions
  rasa_core:
    image: rasa/rasa_core:latest
    networks: ['rasa-network']
    ports:
      - 5005:5005
    volumes:
      - ./models/core:/app/models
      - ./config:/app/config
    command:
      - start
      - --core
      - models
      - -c
      - rest
      - --endpoints
      - config/endpoints_docker.yml
      - -u
      - current/
  rasa_nlu:
    image: rasa/rasa_nlu:latest-full
    networks: ['rasa-network']
    ports:
      - 5000:5000
    volumes:
      - ./models/nlu:/app/models
      - ./config:/app/config
    command:
      - start
      - --path
      - models
      - -c
      - config/nlu_config.yml

networks: {rasa-network: {}}